spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    url: jdbc:mysql://192.168.22.222:3306/sgp?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    jpa:
      show-sql: true
