spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    url: jdbc:mysql://192.168.22.222:3306/sgp?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    jpa:
      show-sql: true
  redis:
    cluster:
      nodes:
        - 192.168.22.109:6379
        - 192.168.22.109:6380
        - 192.168.22.115:6379
        - 192.168.22.115:6380
        - 192.168.22.117:6379
        - 192.168.22.117:6380
    database: 0
    pool:
      max-active: 300
      max-idle: 100
      max-wait: -1
      min-idle: 20
    timeout: 60000
